name: Update README

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *" # Runs every 5 minutes

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Update README file
    - name: Update README
      run: |
        echo "## Updated on $(date)" >> README.md

    # Step 3: Configure Git
    - name: Configure Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    # Step 4: Commit and push changes
    - name: Commit and push changes
      env:
        GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      run: |
        git add README.md
        git commit -m "Automated update to README"
        git push https://${GH_TOKEN}@github.com/${{ github.repository }}.git HEAD:main
